---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution  == "Ubuntu"

  - name: Install apache
    apt:
      name: apache2
      state: latest
    when: ansible_distribution  == "Ubuntu"

  - name: Install php suppport for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution  == "Ubuntu"

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution  == "Fedora"

  - name: Install apache
    yum:
      name: httpd
      state: latest
    when: ansible_distribution  == "Fedora"

  - name: Install php suppport for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution  == "Fedora"
